# Generated by Django 5.2.9 on 2025-12-08 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Book",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("author", models.CharField(max_length=255)),
                (
                    "cover",
                    models.CharField(
                        choices=[("HARD", "Hardcover"), ("SOFT", "Softcover")],
                        default="SOFT",
                        max_length=10,
                    ),
                ),
                ("inventory", models.PositiveIntegerField(default=1)),
                ("daily_fee", models.DecimalField(decimal_places=2, max_digits=6)),
            ],
        ),
    ]
