# Generated by Django 5.2.9 on 2025-12-20 11:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("borrowings", "0002_borrowing_is_paid_borrowing_stripe_session_id_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="borrowing",
            name="is_paid",
        ),
        migrations.RemoveField(
            model_name="borrowing",
            name="stripe_session_id",
        ),
    ]
